# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-23 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picshub', '0002_auto_20200523_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
    ]
